const {test}=require('node:test'), assert=require('node:assert/strict');
const {createDispatcher}=require('../dispatch.cjs');
function fixture(status='finished') {
  const id='a'.repeat(24), records=new Map([[`releases/${id}.json`,{id,commit:'b'.repeat(40),branch:'master',deadline:Date.now()+900000,appId:'6746115397',version:'1.0.1',buildNumber:'12'}],['active.json',{id,until:Date.now()+900000}]]), tasks=[], posts=[];
  const store={read:async name=>({value:records.get(name)}), update:async(name,fn)=>{const value=fn(records.get(name));if(value!==undefined)records.set(name,value);return records.get(name);}};
  const options={store,enqueue:async(...args)=>tasks.push(args),cmToken:{value:()=> 'synthetic-token'},logger:{info:()=>{},error:()=>{}},fetchImpl:async(url,options)=>{if(options.method==='POST'){posts.push(JSON.parse(options.body));return {ok:true,json:async()=>({buildId:'verifier-12'})};}return {ok:true,json:async()=>({build:{status,tag:'testflight/example'}})};}};
  return {id,records,tasks,posts,options,dispatch:(...args)=>createDispatcher(options)(...args)};
}
test('tag-triggered verifier uses actual tag instead of reported default branch',async()=>{const f=fixture();await f.dispatch(f.id,'upload-12');assert.equal(f.posts[0].tag,'testflight/example');assert.equal(f.posts[0].branch,undefined);assert.equal(f.posts[0].environment.variables.YR_APPLE_UPLOAD_ID,'upload-12');assert(f.tasks.length);});
test('failed CI clears release lock without claiming Apple failure',async()=>{const f=fixture('failed');await f.dispatch(f.id);assert.equal(f.records.get('active.json').until,0);assert.equal(f.records.get(`releases/${f.id}.json`).result.phase,'CI');assert.equal(f.posts.length,0);});
test('unfinished build waits and post-publish status check does not bypass webhook',async()=>{const f=fixture('building');await f.dispatch(f.id,undefined,'build_status');assert.equal(f.posts.length,0);assert.equal(f.tasks.length,1);const done=fixture();await done.dispatch(done.id,undefined,'build_status');assert.equal(done.posts.length,0);});
test('revoked CI token fails dispatch and recovery remains scheduled',async()=>{const f=fixture();f.options.fetchImpl=async(url,options)=>options.method==='POST'?{ok:false,status:401}:{ok:true,json:async()=>({build:{status:'finished'}})};await assert.rejects(f.dispatch(f.id),/HTTP 401/);assert(f.tasks.length);});
test('active verifier lease suppresses duplicate launch',async()=>{const f=fixture();f.records.get(`releases/${f.id}.json`).leaseUntil=Date.now()+600000;await f.dispatch(f.id);assert.equal(f.posts.length,0);assert.equal(f.tasks.length,1);});

test('completed verification with canceled notification job emits fallback alert',async()=>{const f=fixture('canceled'),errors=[];Object.assign(f.records.get(`releases/${f.id}.json`),{result:{status:'ready'},runId:'verifier-12'});f.options.logger.error=(...args)=>errors.push(args);await f.dispatch(f.id);assert.equal(errors.length,1);assert.equal(f.records.get(`releases/${f.id}.json`).notificationWorkflowState,'canceled');await f.dispatch(f.id);assert.equal(errors.length,1);assert.equal(f.posts.length,0);});

test('notification completion check waits for publishing and records finished job',async()=>{const f=fixture('publishing');Object.assign(f.records.get(`releases/${f.id}.json`),{result:{status:'ready'},runId:'verifier-12'});await f.dispatch(f.id);assert.equal(f.tasks.length,1);assert.equal(f.records.get(`releases/${f.id}.json`).notificationWorkflowState,undefined);f.options.fetchImpl=async()=>({ok:true,json:async()=>({build:{status:'finished'}})});await f.dispatch(f.id);assert.equal(f.records.get(`releases/${f.id}.json`).notificationWorkflowState,'finished');assert.equal(f.posts.length,0);});
