import 'theme_definition.dart';

/// Seed/fallback values only. Loading the dashboard never writes these remotely.
List<ThemeDefinition> defaultDesignThemes() => [
      for (final seed in [
        ('caramel', '焦糖橘棕', '#C86B3C', '#FFF9ED', '#713A24'),
        ('olive', '橄欖綠', '#748C55', '#FFFDF3', '#3E5637'),
        ('teal', '深藍綠', '#347C78', '#FFFFFF', '#174D4A'),
        ('original', '原本藍紫色', '#7088D7', '#FFFFFF', '#284A7E'),
      ])
        ThemeDefinition(id: seed.$1, name: seed.$2, light: {
          'primary': seed.$3,
          'onPrimary': seed.$4,
          'detail': seed.$5,
          'secondary': '#FFFDF1',
          'tertiary': '#FFFFFF',
          'alternate': '#E0E3E7',
          'primaryText': '#333333',
          'secondaryText': '#666666',
          'primaryBackground': '#FDF2CB',
          'secondaryBackground': '#FFFFFF',
          'border': '#B6B6B6',
          'accent1': '#EEBF2B',
          'accent2': '#39D2C0',
          'accent3': '#EE8B60',
          'accent4': '#FFF9ED',
          'success': '#287E55',
          'error': '#B83E49',
          'warning': '#9C6B10',
          'info': '#347C78',
        }, dark: {
          'primary': seed.$3,
          'onPrimary': seed.$4,
          'detail': seed.$4,
          'secondary': '#262D34',
          'tertiary': '#333D46',
          'alternate': '#414B55',
          'primaryText': '#F5F5F0',
          'secondaryText': '#BEC5CC',
          'primaryBackground': '#151A1E',
          'secondaryBackground': '#20272D',
          'border': '#52606B',
          'accent1': '#EEBF2B',
          'accent2': '#39D2C0',
          'accent3': '#EE8B60',
          'accent4': '#414B55',
          'success': '#68BF93',
          'error': '#FF8992',
          'warning': '#F9CF58',
          'info': '#7AC4BF',
        }, metrics: {
          'headingSize': 32,
          'titleSize': 24,
          'bodySize': 16,
          'labelSize': 14,
          'buttonSize': 24,
          'spaceSmall': 8,
          'spaceMedium': 16,
          'spaceLarge': 32,
          'radiusSmall': 16,
          'radiusMedium': 24,
          'hoverDarken': 0.08,
          'pressedDarken': 0.12,
        }),
    ];
