// Generated by tool/generate_privacy_policy.py. Edit assets/jsons/privacy_policy.json.
class PrivacyPolicySection {
  const PrivacyPolicySection(this.title, this.body);
  final String title;
  final String body;
}

const privacyPolicyUpdated = "2026-09-25";
const privacyPolicySections = <PrivacyPolicySection>[
  PrivacyPolicySection("服務與適用範圍",
      "黃絲帶成長學習系統（yellowribbon study system）供黃絲帶愛網關懷協會及其授權合作人員管理學生資料、每日出席、課堂表現與成長紀錄。帳號由管理員建立，不提供公開註冊；App、帳號及所有功能均免費。\n\n本政策包含工作人員輸入的學生、監護人及緊急聯絡人資料。App 供授權人員操作，所管理的紀錄可能包含未成年學生資料。"),
  PrivacyPolicySection("處理的資料與用途",
      "登入 Email、使用者識別碼及帳號資料：用於登入與辨識使用者。\n\n學生姓名、性別、生日、學校、班級地點、身分識別與聯絡資料：用於建立及維護學生紀錄。\n\n監護人與緊急聯絡人的姓名、聯絡方式、工作單位及身分欄位：用於照護與緊急聯繫紀錄。\n\n家庭、經濟、族群、特殊疾病或特殊學生說明、接送需求：用於記錄服務與照護所需資訊。\n\n興趣、能力評估、學習目標、資源及獎助、課程、介紹與備註，以及出席、課堂表現、品格與黃絲帶紀錄：用於學習輔導、紀錄管理及成長報表。\n\n頭像與使用者選擇上傳的照片或檔案：用於學生識別及相關附件管理。\n\n畫面與操作事件、裝置或安裝識別資訊、當機與效能資訊，以及 SDK 推估的粗略地區：用於維護功能、分析使用情形及改善穩定性。\n\n實際處理的資料取決於所填寫或上傳的內容，並非每位學生都有上述所有資料。請只輸入服務必要且有權提供的內容。"),
  PrivacyPolicySection("雲端服務與資料接收者",
      "App 使用 Google Firebase Authentication 處理登入、Cloud Firestore 儲存與同步資料、Cloud Storage 儲存上傳檔案，並使用 Analytics、Crashlytics 與 Performance Monitoring 分析操作、當機和效能。相關資料會依上述用途由雲端服務處理，系統中具相應權限的協會及合作人員可存取業務紀錄。\n\n不同雲端服務的處理位置可能不同；App 僅在台灣供應，不代表所有資料都只在台灣處理。\n\n目前版本未加入向第三方生成式 AI 傳送學生資料的評估功能；日後如增加此功能，將先更新相關告知與使用流程。\n\nFirebase 隱私資訊：https://firebase.google.com/support/privacy\nGoogle 隱私政策：https://policies.google.com/privacy"),
  PrivacyPolicySection("裝置功能",
      "上傳頭像或附件時，App 使用系統提供的照片或檔案選擇功能。請只選擇有權提供的內容。實際權限要求依裝置、系統版本及使用功能而定。\n\n目前版本未提供精確 GPS 定位、通訊錄讀取或廣告投放功能。分析服務仍可能依網路連線資訊推估粗略地區。"),
  PrivacyPolicySection("保存期限與刪除",
      "學生資料於接受服務期間保存；停止接受服務後保留 1 年，期滿由管理員處理刪除。此期限涵蓋相關學生文件、監護人與緊急聯絡人資料、出席與表現紀錄、頭像及附件。現行 App 未提供自動到期刪除功能，由管理員分別處理各類紀錄。\n\n解除安裝 App 不會刪除雲端帳號或紀錄。單一學生文件的刪除，也不代表所有歷史紀錄、帳號與附件已一併清除。若要提出資料刪除請求，請透過下方聯絡方式告知需要處理的範圍。"),
  PrivacyPolicySection("聯絡與資料請求",
      "學生、監護人或帳號使用者如需提出資料查詢、更正或刪除請求，可聯絡 e2755699@gmail.com，由服務負責人受理。\n\n請先提供可聯繫資訊與請求概要，避免直接透過一般電子郵件寄送完整身分證字號、健康紀錄或其他學生資料。"),
  PrivacyPolicySection(
      "政策更新", "政策更新時會在此頁標示更新日期。若資料處理方式有實質改變，將同步調整 App 內告知及 App Store 隱私揭露。"),
];
