name: widgetbook_gallery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  yellow_ribbon_study_growing_system:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  widgetbook_generator: ^3.8.0

flutter:
  uses-material-design: true
