'use strict';
const {before,after,test}=require('node:test');
const {readFileSync}=require('node:fs');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const {doc,setDoc,runTransaction,serverTimestamp}=require('firebase/firestore');
let env;
const trace=JSON.parse(readFileSync('roster-planner-traces.json','utf8'));
function materialize(v){if(v===trace.timestampMarker)return serverTimestamp();if(Array.isArray(v))return v.map(materialize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,materialize(x)]));return v;}
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-yellow-ribbon-roster',firestore:{host:'127.0.0.1',port:Number(process.env.ROSTER_RULES_PORT||8190),rules:readFileSync('../roster.rules','utf8')}});await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();for(const [p,d] of Object.entries(trace.fixtures))await setDoc(doc(db,p),materialize(d));});});
after(async()=>env?.cleanup());
test('actual Dart planner reads and writes replay as client transactions',async()=>{for(const [i,step] of trace.transactions.entries()){const db=env.authenticatedContext(step.uid).firestore();try{await runTransaction(db,async tx=>{for(const p of step.reads)await tx.get(doc(db,p));for(const w of step.writes)tx.set(doc(db,w.path),materialize(w.data),{merge:w.merge});});}catch(e){throw new Error(`trace ${i} ${step.input.action} ${step.input.operationId}: ${e.message}`,{cause:e});}}});
test('full profile field ranges fit a real enrollment transaction',async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();for(const [p,d] of Object.entries(trace.fixtures))await setDoc(doc(db,p),materialize(d));});const step=structuredClone(trace.transactions[0]);const student=step.writes.find(w=>w.path==='students/s0').data;for(const k of ['gender','phone','idNumber','school','email','guardianName','guardianIdNumber','guardianCompany','guardianPhone','guardianEmail','emergencyContactName','emergencyContactIdNumber','emergencyContactCompany','emergencyContactPhone','emergencyContactEmail','description','specialDiseaseDescription','specialStudentDescription','pickupRequirementDescription','studentIntroduction','motto','interest','abilityEvaluation','learningGoals','resourcesAndScholarships','talentClass','specialCourse'])student[k]='x'.repeat(10000);for(const k of ['economicStatus','familyStatus','ethnicStatus'])student[k]=20;for(const k of ['hasSpecialDisease','isSpecialStudent','needsPickup'])student[k]=true;student.birthday=trace.timestampMarker;const db=env.authenticatedContext(step.uid).firestore();await runTransaction(db,async tx=>{for(const p of step.reads)await tx.get(doc(db,p));for(const w of step.writes)tx.set(doc(db,w.path),materialize(w.data),{merge:w.merge});});});
