'use strict';
const {before,after,beforeEach,test}=require('node:test');
const {readFileSync}=require('node:fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,updateDoc,writeBatch,serverTimestamp}=require('firebase/firestore');
let env;
const trace=JSON.parse(readFileSync('roster-planner-traces.json','utf8'));
const textKeys=['gender','phone','idNumber','school','email','guardianName','guardianIdNumber','guardianCompany','guardianPhone','guardianEmail','emergencyContactName','emergencyContactIdNumber','emergencyContactCompany','emergencyContactPhone','emergencyContactEmail','description','specialDiseaseDescription','specialStudentDescription','pickupRequirementDescription','studentIntroduction','motto','interest','abilityEvaluation','learningGoals','resourcesAndScholarships','talentClass','specialCourse'];
function val(v){if(v===trace.timestampMarker)return serverTimestamp();if(Array.isArray(v))return v.map(val);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,val(x)]));return v;}
function plan(){return structuredClone(trace.transactions[0]);}
function commit(step){const db=env.authenticatedContext(step.uid).firestore(),b=writeBatch(db);for(const w of step.writes)b.set(doc(db,w.path),val(w.data),{merge:w.merge});return b.commit();}
before(async()=>env=await initializeTestEnvironment({projectId:'demo-yellow-ribbon-roster',firestore:{host:'127.0.0.1',port:Number(process.env.ROSTER_RULES_PORT||8190),rules:readFileSync('../roster.rules','utf8')}}));
after(async()=>env?.cleanup());
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();for(const [p,d] of Object.entries(trace.fixtures))await setDoc(doc(db,p),val(d));});});
for(const [label,mutate] of Object.entries({missingReceipt:s=>s.writes=s.writes.filter(w=>!w.path.startsWith('record_operations/')),wrongStudent:s=>s.writes.find(w=>w.path.startsWith('record_operations/')).data.result.studentId='victim',wrongAction:s=>s.writes.find(w=>w.path.startsWith('record_operations/')).data.action='saveRecords',wrongOperation:s=>s.writes.find(w=>w.path.startsWith('record_operations/')).path='record_operations/other',receiptOnly:s=>s.writes=s.writes.filter(w=>w.path.startsWith('record_operations/')),badFirstText:s=>s.writes.find(w=>w.path==='students/s0').data.gender={},badLastText:s=>s.writes.find(w=>w.path==='students/s0').data.specialCourse=42,overlongText:s=>s.writes.find(w=>w.path==='students/s0').data.motto='x'.repeat(10001)}))test('atomic profile rejects '+label,async()=>{const step=plan();mutate(step);await assertFails(commit(step));});
test('atomic profile rejects reuse of an existing receipt',async()=>{const step=plan(),r=step.writes.find(w=>w.path.startsWith('record_operations/'));await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),r.path),val(r.data)));step.writes=step.writes.filter(w=>w!==r);await assertFails(commit(step));});
test('all 27 profile text fields update together at their full bounds',async()=>{const step=plan();await commit(step);const db=env.authenticatedContext(step.uid).firestore(),b=writeBatch(db);b.update(doc(db,'students/s0'),{...Object.fromEntries(textKeys.map(k=>[k,'y'.repeat(10000)])),revision:2,updatedAt:serverTimestamp(),updatedBy:step.uid,lastOperationId:'profile_full'});b.set(doc(db,'record_operations/profile_full'),{uid:step.uid,hash:'a'.repeat(64),action:'updateProfile',result:{studentId:'s0',revision:2,locationIds:['A']},locationIds:['A'],createdAt:serverTimestamp()});await assertSucceeds(b.commit());});
test('attachment direct writes retain field validation',async()=>{await commit(plan());const db=env.authenticatedContext('m').firestore();await assertFails(updateDoc(doc(db,'students/s0'),{avatar:{bad:true}}));await assertFails(updateDoc(doc(db,'students/s0'),{profileFileName:'x'.repeat(10001)}));await assertSucceeds(updateDoc(doc(db,'students/s0'),{avatar:'safe.jpg',profileFileName:null}));});
test('migration markers remain immutable while normal profile and session updates work',async()=>{await commit(plan());await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await updateDoc(doc(db,'student_summaries/s0'),{rosterMigrationId:'migration'});await setDoc(doc(db,'class_sessions/2026-10-01.A'),{locationId:'A',dateKey:'2026-10-01',status:'legacyUnverified',revision:0,rosterMigrationId:'migration'});});const db=env.authenticatedContext('m').firestore(),b=writeBatch(db);b.update(doc(db,'students/s0'),{name:'renamed',revision:2,updatedAt:serverTimestamp(),updatedBy:'m',lastOperationId:'rename'});b.update(doc(db,'student_summaries/s0'),{name:'renamed'});b.set(doc(db,'record_operations/rename'),{uid:'m',hash:'a'.repeat(64),action:'updateProfile',result:{studentId:'s0'},locationIds:['A'],createdAt:serverTimestamp()});await assertSucceeds(b.commit());const held=writeBatch(db);held.update(doc(db,'class_sessions/2026-10-01.A'),{status:'held',revision:1,reason:'',updatedBy:'m',updatedAt:serverTimestamp(),lastOperationId:'held'});held.set(doc(db,'record_operations/held'),{uid:'m',hash:'a'.repeat(64),action:'setSession',result:{},locationIds:['A'],createdAt:serverTimestamp()});await assertSucceeds(held.commit());await assertFails(updateDoc(doc(db,'student_summaries/s0'),{rosterMigrationId:'forged'}));});
test('receipt owner must be the writing actor',async()=>{const step=plan();step.writes.find(w=>w.path.startsWith('record_operations/')).data.uid='t';await assertFails(commit(step));});
test('teacher cannot enroll a student through a forged profile receipt',async()=>{const step=plan();step.uid='t';for(const w of step.writes){if(w.data.updatedBy)w.data.updatedBy='t';if(w.data.uid)w.data.uid='t';}await assertFails(commit(step));});
test('foreign-site teacher cannot use a valid profile receipt to edit another site',async()=>{await commit(plan());await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'staff_access/foreign'),{active:true,role:'teacher',locationIds:['B']}));const db=env.authenticatedContext('foreign').firestore(),b=writeBatch(db);b.update(doc(db,'students/s0'),{motto:'forged',revision:2,updatedBy:'foreign',updatedAt:serverTimestamp(),lastOperationId:'foreign'});b.set(doc(db,'record_operations/foreign'),{uid:'foreign',hash:'b'.repeat(64),action:'updateProfile',result:{studentId:'s0'},locationIds:['B'],createdAt:serverTimestamp()});await assertFails(b.commit());});
test('one receipt cannot authorize updates to two students',async()=>{await commit(plan());await commit(structuredClone(trace.transactions[1]));const db=env.authenticatedContext('m').firestore(),b=writeBatch(db);for(const sid of ['s0','s1'])b.update(doc(db,'students/'+sid),{motto:'changed',revision:2,updatedBy:'m',updatedAt:serverTimestamp(),lastOperationId:'two_students'});b.set(doc(db,'record_operations/two_students'),{uid:'m',hash:'b'.repeat(64),action:'updateProfile',result:{studentId:'s0'},locationIds:['A'],createdAt:serverTimestamp()});await assertFails(b.commit());});
