"""Generate the offline Flutter policy and public page from the same text."""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
policy = json.loads((ROOT / 'assets/jsons/privacy_policy.json').read_text(encoding='utf-8'))
quote = lambda text: json.dumps(text, ensure_ascii=False).replace('$', r'\$')
dart = "// Generated by tool/generate_privacy_policy.py. Edit assets/jsons/privacy_policy.json.\n"
dart += "class PrivacyPolicySection {\n  const PrivacyPolicySection(this.title, this.body);\n  final String title;\n  final String body;\n}\n"
dart += f"const privacyPolicyUpdated = {quote(policy['updated'])};\n"
dart += 'const privacyPolicySections = <PrivacyPolicySection>[\n'
dart += ''.join(f"  PrivacyPolicySection({quote(s['title'])}, {quote(s['body'])}),\n" for s in policy['sections'])
dart += '];\n'
target = ROOT / 'lib/domain/model/privacy_policy.dart'
target.write_text(dart, encoding='utf-8')

sections = ''.join('<section><h2>' + html.escape(s['title']) + '</h2>' +
                   ''.join('<p>' + html.escape(p) + '</p>' for p in s['body'].split('\n\n')) +
                   '</section>' for s in policy['sections'])
page = '''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>黃絲帶成長學習系統｜隱私權政策</title>
<style>body{font-family:system-ui,sans-serif;max-width:860px;margin:auto;padding:32px 20px;line-height:1.85;color:#222;background:#fff}h1{font-size:1.8rem;line-height:1.4}h2{font-size:1.3rem;margin-top:2rem}p{white-space:pre-line;overflow-wrap:anywhere}footer{border-top:1px solid #ddd;margin-top:32px;padding-top:16px}a{color:#294ab1}</style></head><body>
<header><p>黃絲帶成長學習系統</p><h1>隱私權政策</h1><p>更新日期：''' + html.escape(policy['updated']) + '</p></header><main>' + sections + '''</main>
<footer><a href="mailto:e2755699@gmail.com">聯絡服務負責人</a> · <a href="https://firebase.google.com/support/privacy">Firebase 隱私資訊</a> · <a href="https://policies.google.com/privacy">Google 隱私政策</a></footer></body></html>'''
site = ROOT / 'docs/privacy-site'
site.mkdir(exist_ok=True)
(site / 'index.html').write_text(page, encoding='utf-8')
(site / '.nojekyll').touch()
print('Generated offline policy and public HTML from the same 7 sections.')
